# SPDX-License-Identifier: Apache-2.0
"""The CLIENT half of the two-implementation tree-hash agreement (spec §9.3).

``law.tree_hash`` is a from-the-specification reimplementation of
``benchmark-v2/validator/receipt.py::tree_hash``. It has to be: this package is Apache-2.0 with
zero dependencies and the six admission trees are UNLICENSED data it fetches, so importing the
canonical function is neither licensable nor sound (a tree that vouched for itself would vouch for
anything). Two implementations of one hash is exactly where a silent divergence produces a
validator whose verdict nobody else can reproduce.

So the two are pinned to each other by DATA. ``fixtures/tree-hash-golden.v1.json`` is GENERATED by
the canonical implementation (``v5/tests/tree_hash_golden.py`` in the coordinator repository) and
committed byte-identically in both repositories. The coordinator's test asserts
"canonical == fixture"; this one asserts "fixture == client". Both pin the fixture's own sha256, so
the two copies cannot drift apart without one side going red.

If this file fails, do NOT edit the expected roots. One of two things happened: the canonical rule
changed (in which case every signed receipt's ``code_roots`` moved and that is the news), or this
reimplementation broke.
"""
from __future__ import annotations

import base64
import hashlib
import json
import pathlib

import pytest

from coretex_validator import law

FIXTURE_PATH = pathlib.Path(__file__).resolve().parent / "fixtures" / "tree-hash-golden.v1.json"
#: The SAME constant the coordinator's ``v5/tests/test_tree_hash_golden.py`` pins. One file, one
#: hash, two repositories: an edit to either copy that is not mirrored turns a test red.
FIXTURE_SHA256 = "6b9997bf807028e7b764f1b7c81edc5db15bf6c3ce24fdb6444b8e3dd75ca7c9"


@pytest.fixture(scope="module")
def raw():
    return FIXTURE_PATH.read_bytes()


@pytest.fixture(scope="module")
def document(raw):
    return json.loads(raw.decode("utf-8"))


def materialize(vector, dest):
    for rel, b64 in sorted(vector["files"].items()):
        path = dest.joinpath(*rel.split("/"))
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(base64.b64decode(b64))
    return dest


def test_the_fixture_is_the_bytes_the_coordinator_generated(raw):
    assert hashlib.sha256(raw).hexdigest() == FIXTURE_SHA256


def test_every_golden_vector_reproduces_under_the_client_implementation(document, tmp_path):
    """The agreement itself. Each vector is materialized and hashed by THIS package's code."""
    failures = []
    for vector in document["vectors"]:
        dest = materialize(vector, tmp_path / vector["name"])
        observed = law.tree_hash(str(dest), tuple(vector["exclude"]))
        if observed != vector["expected_root"]:
            failures.append(f"{vector['name']}: {observed} != {vector['expected_root']} "
                            f"({vector['why']})")
    assert not failures, "\n".join(failures)


def test_the_in_memory_form_agrees_with_the_on_disk_form(document, tmp_path):
    """``tree_hash_from_files`` is what verifies a fetched tar; it must not be a second rule."""
    for vector in document["vectors"]:
        files = {rel: base64.b64decode(b64) for rel, b64 in vector["files"].items()}
        assert law.tree_hash_from_files(files, tuple(vector["exclude"])) \
            == vector["expected_root"], vector["name"]


def test_the_client_carries_the_same_exclusion_rule(document):
    assert sorted(law.TREE_EXCLUDE_DIRS) == sorted(document["exclude_dirs"])
    assert list(law.TREE_EXCLUDE_SUFFIXES) == document["exclude_suffixes"]
    assert {k: list(v) for k, v in law.KEY_MATERIAL_EXCLUSIONS.items()} \
        == document["key_material_exclusions"]


def test_an_empty_tree_hashes_to_sha256_of_nothing(document, tmp_path):
    empty = tmp_path / "nothing"
    empty.mkdir()
    assert law.tree_hash(str(empty)) == document["empty_tree_root"]
    assert law.tree_hash_from_files({}) == document["empty_tree_root"]


def test_the_line_sort_is_over_lines_not_path_components():
    """The one place a reasonable-looking implementation silently disagrees.

    ``b.py`` precedes ``b/a.py`` because ``.`` (0x2E) < ``/`` (0x2F). Sorting the paths by
    component — the natural thing to write — reverses them and produces a different root. Asserted
    directly here as well as through the vector, because this is the trap.
    """
    files = {"b.py": b"one\n", "b/a.py": b"two\n"}
    one = hashlib.sha256(b"one\n").hexdigest()
    two = hashlib.sha256(b"two\n").hexdigest()
    expected = hashlib.sha256(
        ("b.py\0" + one + "\n" + "b/a.py\0" + two + "\n").encode("utf-8")).hexdigest()
    assert law.tree_hash_from_files(files) == expected
    # the wrong order, spelled out, so the assertion above cannot pass by accident
    wrong = hashlib.sha256(
        ("b/a.py\0" + two + "\n" + "b.py\0" + one + "\n").encode("utf-8")).hexdigest()
    assert expected != wrong


def test_key_material_absence_and_presence_agree(document):
    roots = {v["name"]: v["expected_root"] for v in document["vectors"]}
    assert roots["key-material-excluded-present"] == roots["key-material-excluded-absent"]
    # ...and the client's own exclusion lookup is what produces that agreement.
    assert law.key_material_exclusions("benchmark-v2/validator") \
        == ("keys/validator_seed.test.hex",)
    assert law.key_material_exclusions("benchmark-v2/frontier") == ()


def test_the_hash_is_not_vacuously_constant(document):
    roots = {v["name"]: v["expected_root"] for v in document["vectors"]}
    assert roots["content-sensitivity"] != roots["single-file"]
    assert roots["name-sensitivity"] != roots["single-file"]


def test_excluded_directories_are_invisible_at_any_depth(tmp_path):
    """Asserted structurally as well as by vector: the rule is about names, at every level."""
    base = tmp_path / "tree"
    (base / "pkg").mkdir(parents=True)
    (base / "pkg" / "mod.py").write_bytes(b"x\n")
    clean = law.tree_hash(str(base))
    for junk in ("__pycache__/a.pyc", "pkg/__pycache__/b.pyc", ".pytest_cache/c",
                 "evidence/d.json", "pkg/evidence/e.json", "pkg/mod.pyc"):
        path = base.joinpath(*junk.split("/"))
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"junk")
    assert law.tree_hash(str(base)) == clean


def test_a_missing_tree_is_an_error_not_an_empty_hash(tmp_path):
    with pytest.raises(law.LawVerifyError):
        law.tree_hash(str(tmp_path / "does-not-exist"))
